name: Deploy React App to Azure Storage

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./front-end
env:
  AZURE_WEBAPP_NAME: Front-End-App    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'build'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12'                # set this to the node version to use
  CI: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        # npm run test --if-present
    - name: 'Deploy static web app to Azure blob storage'
      uses: lauchacarro/Azure-Storage-Action@v1.0
      with:
        enabled-static-website: 'true'
        folder: 'front-end/build'
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} 
